name: family-erp
owner: vasu2152004
package: .
kind: wasmer.io/App.v0
meta:
  name: family-erp
  owner: vasu2152004
spec:
  build:
    steps:
    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader
    - name: Install Node dependencies
      run: npm ci
    - name: Build frontend
      run: npm run build
  name: family-erp
  owner: vasu2152004
  package: .
  ports:
  - port: 8080
    protocol: http
  workload:
    command: |
      php artisan key:generate --force
      php artisan migrate --force
      php artisan db:seed --force
      php artisan config:clear
      php artisan route:clear
      php artisan view:clear
      php artisan serve --host=0.0.0.0 --port=8080
    runtime: php
    source: local
    type: web
