name: family-erp
owner: vasu2152004
package: .
kind: wasmer.io/App.v0
meta:
  name: family-erp
  owner: vasu2152004
spec:
  build:
    steps:
    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader
    - name: Install Node dependencies
      run: npm ci
    - name: Build frontend
      run: npm run build
  name: family-erp
  owner: vasu2152004
  package: .
  ports:
  - port: 8080
    protocol: http
  workload:
    env:
      APP_NAME: "Family ERP"
      APP_ENV: "production"
      APP_DEBUG: "false"
      APP_URL: "https://family-erp.wasmer.app"
      LOG_CHANNEL: "stack"
      LOG_LEVEL: "error"
      DB_CONNECTION: "mysql"
      SESSION_DRIVER: "database"
      CACHE_STORE: "database"
      QUEUE_CONNECTION: "database"
      FILESYSTEM_DISK: "local"
    command: |
      # Create storage directories if they don't exist
      echo "Creating storage directories..."
      mkdir -p storage/framework/cache/data
      mkdir -p storage/framework/sessions
      mkdir -p storage/framework/views
      mkdir -p storage/logs
      mkdir -p bootstrap/cache
      
      # Copy .env.example to .env if .env doesn't exist
      echo "Setting up .env file..."
      if [ ! -f .env ]; then
        cp .env.example .env 2>/dev/null || true
      fi
      
      # Set environment variables in .env
      echo "Configuring environment variables..."
      sed -i 's|^APP_ENV=.*|APP_ENV=production|' .env || echo "APP_ENV=production" >> .env
      sed -i 's|^APP_DEBUG=.*|APP_DEBUG=false|' .env || echo "APP_DEBUG=false" >> .env
      sed -i 's|^DB_CONNECTION=.*|DB_CONNECTION=mysql|' .env || echo "DB_CONNECTION=mysql" >> .env
      
      # Update MySQL connection settings from environment variables if they exist
      if [ -n "$DB_HOST" ]; then
        sed -i "s|^DB_HOST=.*|DB_HOST=$DB_HOST|" .env || echo "DB_HOST=$DB_HOST" >> .env
      fi
      if [ -n "$DB_PORT" ]; then
        sed -i "s|^DB_PORT=.*|DB_PORT=$DB_PORT|" .env || echo "DB_PORT=$DB_PORT" >> .env
      fi
      if [ -n "$DB_DATABASE" ]; then
        sed -i "s|^DB_DATABASE=.*|DB_DATABASE=$DB_DATABASE|" .env || echo "DB_DATABASE=$DB_DATABASE" >> .env
      fi
      if [ -n "$DB_USERNAME" ]; then
        sed -i "s|^DB_USERNAME=.*|DB_USERNAME=$DB_USERNAME|" .env || echo "DB_USERNAME=$DB_USERNAME" >> .env
      fi
      if [ -n "$DB_PASSWORD" ]; then
        sed -i "s|^DB_PASSWORD=.*|DB_PASSWORD=$DB_PASSWORD|" .env || echo "DB_PASSWORD=$DB_PASSWORD" >> .env
      fi
      
      # Generate application key if not set
      echo "Generating application key..."
      php artisan key:generate --force 2>&1 || echo "Key generation failed, continuing..."
      
      # Run migrations
      echo "Running migrations..."
      php artisan migrate --force 2>&1 || echo "Migrations failed, continuing..."
      
      # Clear and cache config
      echo "Caching configuration..."
      php artisan config:clear 2>&1 || true
      php artisan config:cache 2>&1 || true
      php artisan route:clear 2>&1 || true
      php artisan route:cache 2>&1 || true
      php artisan view:clear 2>&1 || true
      php artisan view:cache 2>&1 || true
      
      # Start the server
      echo "Starting Laravel server..."
      php artisan serve --host=0.0.0.0 --port=8080
    runtime: php
    source: local
    type: web
