name: family-erp
owner: vasu2152004
package: .
kind: wasmer.io/App.v0
meta:
  name: family-erp
  owner: vasu2152004
spec:
  build:
    steps:
    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader
    - name: Install Node dependencies
      run: npm ci
    - name: Build frontend
      run: npm run build
  name: family-erp
  owner: vasu2152004
  package: .
  ports:
  - port: 8080
    protocol: http
  workload:
    env:
      APP_NAME: "Family ERP"
      APP_ENV: "production"
      APP_DEBUG: "false"
      APP_URL: "https://family-erp.wasmer.app"
      LOG_CHANNEL: "stack"
      LOG_LEVEL: "error"
      DB_CONNECTION: "mysql"
      SESSION_DRIVER: "database"
      CACHE_STORE: "database"
      QUEUE_CONNECTION: "database"
      FILESYSTEM_DISK: "local"
      MYSQL_ATTR_SSL_CA: "/app/ca.pem"
      MYSQL_ATTR_SSL_VERIFY_SERVER_CERT: "true"
    command: |
      cd /app
      mkdir -p storage/framework/cache/data storage/framework/sessions storage/framework/views storage/logs bootstrap/cache
      echo "Testing database connection..."
      php artisan tinker --execute="DB::connection()->getPdo(); echo 'Database connected successfully';" || echo "Database connection failed"
      echo "Running migrations..."
      php artisan migrate --force || true
      echo "Starting server..."
      exec php artisan serve --host=0.0.0.0 --port=8080
    runtime: php
    source: local
    type: web